=== legiarc/Llenguatge_de_marques/Microtasca 4/restaurant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name="restaurant">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element name="plat" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="codi" type="nonemptystring"/>
                        <xs:element name="nom" type="nonemptystring"/>
                        <xs:element name="descripció" type="nonemptystring" minOccurs="0"/>
                        <xs:element name="preu" type="nonemptydouble"/>
                        <xs:element name="alergens" type="nonemptystring" minOccurs="0"/>
                        <xs:element name="tipus">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Entrant"/>
                                    <xs:enumeration value="Plat principal"/>
                                    <xs:enumeration value="Segon plat"/>
                                    <xs:enumeration value="Postre"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="menu" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="plat_menu" maxOccurs="unbounded">
                            <xs:complexType>
                                    <xs:all>
                                        <xs:element name="nom_plat" type="nonemptystring"/>
                                        <xs:element name="descripció" type="nonemptystring" minOccurs="0"/>
                                        <xs:element name="tipus">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Entrant"/>
                                                    <xs:enumeration value="Plat principal"/>
                                                    <xs:enumeration value="Segon plat"/>
                                                    <xs:enumeration value="Postre"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                            </xs:complexType>
                        </xs:element>    
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="nonemptystring">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:pattern value="\S.*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonemptydouble">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.1"/>
            <xs:pattern value="[0-9]+(\.[0-9])?"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== legiarc/Llenguatge_de_marques/Microtasca 4/resturantxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<restaurant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\marc\Documents\HTML\Microtasca 4\restaurant.xsd">
    <plat>
        <codi>001</codi>
        <nom>Pizza pepperoni</nom>
        <preu>10.5</preu>
        <tipus>Plat principal</tipus>
    </plat>
    <menu>
        <plat_menu>
            <nom_plat>Croquetes de pernil salat</nom_plat>
            <tipus>Entrant</tipus>
        </plat_menu>
        <plat_menu>
            <nom_plat>Paella</nom_plat>
            <tipus>Plat principal</tipus>
            <descripció>Plat d'arros original de Valencia</descripció>
        </plat_menu>
        <plat_menu>
            <nom_plat>Peix a la planxa</nom_plat>
            <tipus>Segon plat</tipus>
        </plat_menu>
        <plat_menu>
            <nom_plat>Tiramisu</nom_plat>
            <tipus>Postre</tipus>
        </plat_menu>
    </menu>
</restaurant>
