=== legiarc/Llenguatge_de_marques/Microtasca 4/restaurant.dtd
<!ELEMENT restaurant (plat*, menu*)>

<!ELEMENT plat (codi, nom, preu, descripcio?, alergens?, tipus)>
<!ELEMENT codi (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT alergens (#PCDATA)>
<!ELEMENT tipus (#PCDATA)>


<!ELEMENT menu (plat_menu+)>

<!ELEMENT plat_menu (nom_plat, tipus_plat, descripcio_plat?)>
<!ELEMENT nom_plat (#PCDATA)>
<!ELEMENT tipus_plat (#PCDATA)>
<!ELEMENT descripcio_plat (#PCDATA)>

=== legiarc/Llenguatge_de_marques/Microtasca 4/Restaurant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurant SYSTEM "C:\Users\marc\Documents\HTML\Microtasca 4\restaurant.dtd">
<restaurant>
        <plat tipus="Plat_principal">
            <codi>001</codi>
            <nom>Pizza pepperoni</nom>
            <preu>11,99</preu>
            <descripcio>Pizza a l'estil napolità coronada amb rodanxes de pepperoni</descripcio>
            <alergens>Gluten</alergens>
        </plat>
        <plat tipus="Entrant">
            <codi>002</codi>
            <nom>Croquetes de pernil salat</nom>
            <preu>6,5</preu>
            <descripcio></descripcio>
            <alergens>Gluten</alergens>
        </plat>
        <plat tipus="Postre">
            <codi>003</codi>
            <nom>Tiramisú</nom>
            <preu>8</preu>
            <descripcio>Postre típic italià fet amb pa de pessic, formatge mascarpone, café i decorat amb cacau en pols</descripcio>
            <alergens>Lactosa</alergens>
        </plat>
        <plat tipus="Segon_plat">
            <codi>004</codi>
            <nom>Salmó a la planxa</nom>
            <preu>15,85</preu>
            <descripcio></descripcio>
            <alergens>Peix</alergens>
        </plat>
        <menu>

            <plat_menu tipus="Entrant">
                <nom_plat>Taula d'embotits i formatge</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>
            
            <plat_menu tipus="Plat_principal">
                <nom_plat>Llomillo al vi blanc</nom_plat>
                <descripcio_plat>Peça de carn molt tendre cuinada dins vi blanc</descripcio_plat>
            </plat_menu>

            <plat_menu tipus="Segon_plat">
                <nom_plat>Llubina a la llimona</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>

            <plat_menu tipus="Postre">
                <nom_plat>Pastís de formatge</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>
        </menu>
        <menu>
            <plat_menu tipus="Entrant">
                <nom_plat>Amanida césar</nom_plat>
                <descripcio_plat>Amanida amb crostons, pitera de pollastre arrebossat i una salsa clàssica</descripcio_plat>
            </plat_menu>
            
            <plat_menu tipus="Plat_principal">
                <nom_plat>Bacallà a la planxa</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>

            <plat_menu tipus="Segon_plat">
                <nom_plat>Porcella rostida</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>
            
            <plat_menu tipus="Postre">
                <nom_plat>Peça de fruita variada</nom_plat>
                <descripcio_plat></descripcio_plat>
            </plat_menu>
        </menu>
</restaurant>
